using AspnetCore.Data.Entities;
using AspnetCore.Data.Models;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace AspnetCore.Data;

public class DataContext : DbContext
{
    public DataContext(DbContextOptions<DataContext> options) : base(options)
    {
    }

    public DbSet<AuditLog> AuditLogs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        // Configure using Fluent API
        modelBuilder.ApplyConfigurationsFromAssembly(typeof(AuditLogConfiguration).Assembly);
    }

    public virtual int SaveChanges(AuditLogCreatingModel auditLogCreating = null)
    {
        var auditEntries = new List<AuditEntryModel>();
        if (auditLogCreating != null)
            auditEntries = OnBeforeSaveChanges(auditLogCreating);
        var result = base.SaveChanges();
        OnAfterSaveChanges(auditEntries);
        return result;
    }

    public virtual async Task<int> SaveChangesAsync(AuditLogCreatingModel auditLogCreating = null)
    {
        var auditEntries = new List<AuditEntryModel>();
        if (auditLogCreating != null)
            auditEntries = OnBeforeSaveChanges(auditLogCreating);
        var result = await base.SaveChangesAsync();
        await OnAfterSaveChangesAsync(auditEntries);
        return result;
    }

    private List<AuditEntryModel> OnBeforeSaveChanges(AuditLogCreatingModel auditLogCreating)
    {
        ChangeTracker.DetectChanges();
        var auditEntries = new List<AuditEntryModel>();
        foreach (var entry in ChangeTracker.Entries())
        {
            if (entry.Entity is AuditLog || entry.State == EntityState.Detached || entry.State == EntityState.Unchanged)
                continue;
            var auditEntry = new AuditEntryModel(entry)
            {
                Method = auditLogCreating.Method,
                TableName = entry.Entity.GetType().Name,
                CreatedUserId = auditLogCreating.CreatedUserId
            };
            auditEntries.Add(auditEntry);
            foreach (var property in entry.Properties)
            {
                if (property.IsTemporary)
                {
                    // value will be generated by the database, get the value after saving
                    auditEntry.TemporaryProperties.Add(property);
                    continue;
                }

                string propertyName = property.Metadata.Name;

                if (property.Metadata.IsPrimaryKey())
                {
                    auditEntry.KeyValues[propertyName] = property.CurrentValue;
                    continue;
                }

                switch (entry.State)
                {
                    case EntityState.Added:
                        auditEntry.Type = AuditLogType.Create;
                        auditEntry.NewValues[propertyName] = property.CurrentValue;
                        break;
                    case EntityState.Deleted:
                        auditEntry.Type = AuditLogType.Delete;
                        auditEntry.OldValues[propertyName] = property.OriginalValue;
                        break;
                    case EntityState.Modified:
                        if (auditEntry.Method == "DELETE")
                        {
                            auditEntry.Type = AuditLogType.Delete;
                            auditEntry.OldValues[propertyName] = property.OriginalValue;
                        }
                        else
                        {
                            if (property.IsModified)
                            {
                                if (JsonConvert.SerializeObject(property.OriginalValue) !=
                                    JsonConvert.SerializeObject(property.CurrentValue))
                                    auditEntry.ChangedColumns.Add(propertyName);
                                auditEntry.Type = AuditLogType.Update;
                                auditEntry.OldValues[propertyName] = property.OriginalValue;
                                auditEntry.NewValues[propertyName] = property.CurrentValue;
                            }
                        }
                        break;
                }
            }
        }
        foreach (var auditEntry in auditEntries.Where(_ => !_.HasTemporaryProperties))
        {
            AuditLogs.Add(auditEntry.ToAudit());
        }

        return auditEntries.Where(_ => _.HasTemporaryProperties).ToList();
    }

    private Task OnAfterSaveChangesAsync(List<AuditEntryModel> auditEntries)
    {
        if (auditEntries == null || auditEntries.Count == 0)
            return Task.CompletedTask;

        foreach (var auditEntry in auditEntries)
        {
            foreach (var prop in auditEntry.TemporaryProperties)
            {
                if (prop.Metadata.IsPrimaryKey())
                {
                    auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                }
                else
                {
                    auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                }
            }

            AuditLogs.Add(auditEntry.ToAudit());
        }

        return SaveChangesAsync();
    }

    private void OnAfterSaveChanges(List<AuditEntryModel> auditEntries)
    {
        if (auditEntries == null || auditEntries.Count == 0)
            return;

        foreach (var auditEntry in auditEntries)
        {
            foreach (var prop in auditEntry.TemporaryProperties)
            {
                if (prop.Metadata.IsPrimaryKey())
                {
                    auditEntry.KeyValues[prop.Metadata.Name] = prop.CurrentValue;
                }
                else
                {
                    auditEntry.NewValues[prop.Metadata.Name] = prop.CurrentValue;
                }
            }

            AuditLogs.Add(auditEntry.ToAudit());
        }

        SaveChanges();
    }
}